pybullet build time: Dec 10 2021 16:29:52
2022-03-08 16:08:11.753240: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:11.774830: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:11.774943: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:11.775313: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-08 16:08:11.776419: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:11.776518: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:11.776595: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:12.019415: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:12.019534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:12.019608: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-08 16:08:12.019690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2157 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-03-08 16:08:12.019913: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-03-08 16:08:12.554795: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
loading weights
argv[0]=
argv[0]=
230929
240830















































































































































































































































































































































































100%|█████████████████████████████████████████████████████████████| 1000/1000 [12:17<00:00,  1.36it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 169, in _get_ffmpeg_api
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/soheil/Sync/unh/courses/hri/project/src/Soheil/sac.py", line 382, in <module>
    with imageio.get_writer("video/random_agent.mp4", fps=60) as video:
  File "/usr/lib/python3.10/site-packages/imageio/v2.py", line 126, in get_writer
    return image_file.legacy_get_writer(**kwargs)
  File "/usr/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py", line 150, in legacy_get_writer
    return self._format.get_writer(self._request)
  File "/usr/lib/python3.10/site-packages/imageio/core/format.py", line 204, in get_writer
    return self.Writer(self, request)
  File "/usr/lib/python3.10/site-packages/imageio/core/format.py", line 281, in __init__
    self._open(**self.request.kwargs.copy())
  File "/usr/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 557, in _open
    self._ffmpeg_api = _get_ffmpeg_api()
  File "/usr/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 171, in _get_ffmpeg_api
    raise ImportError(
ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'